sudo: required
services:
  - docker

before_install:
  - docker build --no-cache -t haykyegh/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true haykyegh/docker-react npm run test -- --coverage
